version: '3'

services:
  mariadb:
    container_name: mariadb-inception
    image: mariadb-inception
    env_file: ./.env
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"

  nginx:
    image: nginx-inception
    depends_on:
    - wordpress
    container_name: nginx-inception
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
    - "443:443"
    restart: on-failure
  
  wordpress:
    container_name: wordpress-inception
    image: wordpress-inception
    env_file: ./.env
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose:
    - "9000"

volumes:
  wordpress:
    name: wordpress-inception
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wordpress'
  mariadb:
    name: mariadb-inception
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '~/data/mysql'

networks:
  inception:
    name: network-inception
    driver: bridge